all:
	./make_nutanix_manifest.sh deepomatic-demo-app ../demo/manifest.yml ../generated/deepomatic-demo-manifest.yml
	./make_nutanix_manifest.sh deepomatic-demo-app ../demo/stage-manifest.yml ../generated/deepomatic-stage-manifest.yml
	./make_nutanix_manifest.sh deepomatic-runtime-app ../runtime/manifest.yml ../generated/deepomatic-app-manifest.yml
