apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT_NAME}
  labels:
    app: ${DEPLOYMENT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app: ${DEPLOYMENT_NAME}
    spec:
      restartPolicy: Always
      volumes:
        - name: neural-worker-resources
          emptyDir: {}
      ${DOCKER_HUB_SECRET_NAME}

      containers:
      - name: runtime
        image: ${DOCKER_IMAGE_NAME}
        env:
        - name: AMQP_URL
          value: amqp://user:password@localhost:5672/nutanix
        - name: DRAW_DEMO
          value: "1"
        - name: PROCESS_EACH_N_FRAMES
          value: "8"
        ${NATS_ENDPOINT}
        ${NATS_SRC_TOPIC}
        ${NATS_DST_TOPIC}

      - name: neural-worker
        image: deepomatic/run-neural-worker:${DEEPOMATIC_RUN_VERSION}
        env:
        - name: ALLOW_NO_GPU
          value: "1"
        - name: AUTOSTART_WORKER
          value: "false"
        - name: AMQP_URL
          value: amqp://user:password@localhost:5672/nutanix
        - name: MODEL_LOCAL_ROOT
          value: /var/lib/deepomatic/resources
        - name: LICENSE_FILENAME
          value: /var/lib/deepomatic/resources/license.bin
        - name: WORKFLOWS_PATH
          value: /var/lib/deepomatic/resources/workflows.json
        volumeMounts:
          - mountPath: /var/lib/deepomatic/
            name: neural-worker-resources

      - name: resource-server
        image: deepomatic/run-resource-server:${DEEPOMATIC_RUN_VERSION}
        env:
        - name: DEEPOMATIC_API_URL
          value: https://api.deepomatic.com
        - name: DEEPOMATIC_APP_ID
          value: "${DEEPOMATIC_APP_ID}"
        - name: DEEPOMATIC_API_KEY
          value: "${DEEPOMATIC_API_KEY}"
        - name: DEEPOMATIC_SITE_ID
          value: "${DEEPOMATIC_SITE_ID}"
        - name: DOWNLOAD_ON_STARTUP
          value: "1"
        volumeMounts:
          - mountPath: /app/services/worker-nn
            name: neural-worker-resources

      - name: rabbitmq
        image: rabbitmq:3.6
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: user
        - name: RABBITMQ_DEFAULT_PASS
          value: password
        - name: RABBITMQ_DEFAULT_VHOST
          value: nutanix

      ${NATS_SERVICE}
